 CREATE DATABASE PIZZAHUT;
 USE PIZZAHUT;
 CREATE TABLE ORDERS(
 OERDER_ID INT PRIMARY KEY,
 ORDER_DATE DATE NOT NULL,
 ORDER_TIME TIME NOT NULL
 );
 
CREATE TABLE ORDERS_DETAILS(
ORDERS_DETAILS_ID INT PRIMARY KEY,
ORDER_ID INT NOT NULL,
PIZZA_ID TEXT NOT NULL,
QUANTITY INT NOT null
);


 